Cu 57wk7q clark chen
roushanyyzz/Lottery pull request #6
Opened 2020-11-23 13:23 UTC by Clark-spec

Create entity
CRUD for lotteryPool

2020-11-23 14:03 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +    public String addLotteryPoolOwner(
add-owner

2020-11-23 14:03 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +        String newLotteryPool = lotteryPoolService.createLotteryPool(lotteryPoolSize);
createNewLotteryPool(
            @RequestParam Long lotteryPoolSize
)

2020-11-23 14:04 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +    public String querySelected(){
Do not use hump names in urls

2020-11-23 14:04 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +    public String queryNotSelected(){
Do not use hump names in urls

2020-11-23 14:05 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +    public String queryAll(){
Do not use hump names in urls

2020-11-23 14:05 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryHolderService.java
> +        System.out.println(LotteryHolderStatusEnum.ENABLED.getValue());
Don't print

2020-11-23 14:07 UTC, roushanyyzz requested changes
Update

2020-11-23 14:07 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +        LOGGER.info("Start to create new lottery pool, size{}",lotteryPoolSize);
lotteryPoolSize use Int

2020-11-23 14:31 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +    public String addLotteryPoolOwner(
update

2020-11-23 14:32 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +        String newLotteryPool = lotteryPoolService.createLotteryPool(lotteryPoolSize);
update

2020-11-23 14:32 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +    public String querySelected(){
update

2020-11-23 14:32 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +    public String queryNotSelected(){
update

2020-11-23 14:33 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +    public String queryAll(){
update

2020-11-23 14:33 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryHolderService.java
> +        System.out.println(LotteryHolderStatusEnum.ENABLED.getValue());
update

2020-11-23 14:34 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +        LOGGER.info("Start to create new lottery pool, size{}",lotteryPoolSize);
update

2020-11-23 14:56 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +        String newLotteryPool = lotteryPoolService.createLotteryPool(lotteryPoolSize);
public String createLotteryPool(
            @RequestParam int lotteryPoolSize
) {

2020-11-23 14:59 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/controller/api/LotteryPoolApiController.java
> +        String newLotteryPool = lotteryPoolService.createLotteryPool(lotteryPoolSize);
update

2020-11-23 15:36 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(LotteryPool.class);
LotteryPool -> LotteryPoolService

2020-11-23 15:36 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +            lotteryPool.setStatus(0);
use enum

2020-11-23 15:37 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +    public LotteryPool findByLotteryPoolNum(Long lotteryPoolNum){
Why number is long?

2020-11-23 15:38 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +        JSONArray lotteryPoolArray = JSON.parseArray(JSON.toJSONString(lotteryPoolList));
Don't use JSONArray lotteryPoolArray = JSON.parseArray(JSON.toJSONString(lotteryPoolList));
 use : return AjaxResult.success(lotteryPoolList);

2020-11-23 15:39 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +            LOGGER.warn("Num is not exit,Num{}", Num);
Num{} add space

2020-11-23 15:42 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +        if ( LotteryPoolStatusEnum.ENABLED.getValue().equals(lotteryPool.getStatus())){
Status just enable and disabled? Has something else?

2020-11-23 15:42 UTC, roushanyyzz commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +            LOGGER.warn("This num has been selected,Num{}", Num);
Space

2020-11-24 05:13 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +            LOGGER.warn("This num has been selected,Num{}", Num);
update

2020-11-24 05:50 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +        if ( LotteryPoolStatusEnum.ENABLED.getValue().equals(lotteryPool.getStatus())){
Status has three.Enable is selected.Disable means no longer effective.Inited is selectable.

2020-11-24 05:52 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +            LOGGER.warn("Num is not exit,Num{}", Num);
update

2020-11-24 05:54 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +        JSONArray lotteryPoolArray = JSON.parseArray(JSON.toJSONString(lotteryPoolList));
update

2020-11-24 05:57 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +    public LotteryPool findByLotteryPoolNum(Long lotteryPoolNum){
update

2020-11-24 05:57 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +            lotteryPool.setStatus(0);
update

2020-11-24 05:58 UTC, Clark-spec commented on lottery-clientapi/src/main/java/com/arbfintech/station/lottery/clientapi/service/LotteryPoolService.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(LotteryPool.class);
update

2020-11-25 14:14 UTC, Clark-spec commented
Show the number

2020-11-25 14:27 UTC, Clark-spec commented
Show the number

2020-11-25 15:14 UTC, Clark-spec commented
update

2020-11-26 05:39 UTC, Clark-spec commented
update

2020-11-26 06:55 UTC, Clark-spec commented
update

2020-12-01 05:54 UTC, closed without merging